name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Cypress
        run: npm install cypress
      - name: Run Cypress Tests
        run: |
          github-script -run main.js
